glibc: sync with upstream 2.19-5
Signed-off-by: Paul Burton <paul@archlinuxmips.org>

diff --git a/glibc/PKGBUILD b/glibc/PKGBUILD
--- a/glibc/PKGBUILD
+++ b/glibc/PKGBUILD
@@ -1,4 +1,4 @@
-# $Id: PKGBUILD 205613 2014-02-10 03:07:48Z allan $
+# $Id: PKGBUILD 213324 2014-05-20 08:17:34Z allan $
 # Maintainer: Allan McRae <allan@archlinux.org>
 
 # toolchain build order: linux-api-headers->glibc->binutils->gcc->binutils->glibc
@@ -8,7 +8,7 @@
 
 pkgname=glibc
 pkgver=2.19
-pkgrel=1.1
+pkgrel=5.1
 pkgdesc="GNU C Library"
 arch=('i686' 'x86_64')
 url="http://www.gnu.org/software/libc"
@@ -22,20 +22,30 @@ backup=(etc/gai.conf
 options=('!strip' 'staticlibs')
 install=glibc.install
 source=(http://ftp.gnu.org/gnu/libc/${pkgname}-${pkgver}.tar.xz{,.sig}
-        glibc-2.18-xattr-compat-hack.patch
+        glibc-2.19-xattr_header.patch
+        glibc-2.19-fix-sign-in-bsloww1-input.patch
+        glibc-2.19-tzselect-default.patch
         locale.gen.txt
         locale-gen)
 md5sums=('e26b8cc666b162f999404b03970f14e4'
          'SKIP'
-         '7ca96c68a37f2a4ab91792bfa0160a24'
+         '39a4876837789e07746f1d84cd8cb46a'
+         '755a1a9d7844a5e338eddaa9a5d974cd'
+         'c772dc99ddd8032ecbf43884ae0cf42e'
          '07ac979b6ab5eeb778d55f041529d623'
-         'b5fd017036fb91199ee76f670da8c15b')
+         '476e9113489f93b348b21e144b6a8fcf')
 
 prepare() {
   cd ${srcdir}/${pkgname}-${pkgver}
   
-  # hack fix for {linux,sys}/xattr.h incompatibility
-  patch -p1 -i $srcdir/glibc-2.18-xattr-compat-hack.patch
+  # fix for {linux,sys}/xattr.h incompatibility - commit fdbe8eae
+  patch -p1 -i $srcdir/glibc-2.19-xattr_header.patch
+
+  # fix issues in sin/cos slow path calculation - commit ffe768a9
+  patch -p1 -i $srcdir/glibc-2.19-fix-sign-in-bsloww1-input.patch
+
+  # fix tzselect with missing TZDIR - commit 893b4f37/c72399fb
+  patch -p1 -i $srcdir/glibc-2.19-tzselect-default.patch
 
   mkdir ${srcdir}/glibc-build
 }
@@ -54,7 +64,7 @@ build() {
   echo "rootsbindir=/usr/bin" >> configparms
 
   # remove hardening options for building libraries
-  CFLAGS=${CFLAGS/-fstack-protector/}
+  CFLAGS=${CFLAGS/-fstack-protector-strong/}
   CPPFLAGS=${CPPFLAGS/-D_FORTIFY_SOURCE=2/}
 
   multiarch="--enable-multi-arch"
@@ -81,8 +91,8 @@ build() {
   
   # re-enable hardening for programs
   sed -i "/build-programs=/s#no#yes#" configparms
-  echo "CC += -fstack-protector -D_FORTIFY_SOURCE=2" >> configparms
-  echo "CXX += -fstack-protector -D_FORTIFY_SOURCE=2" >> configparms
+  echo "CC += -fstack-protector-strong -D_FORTIFY_SOURCE=2" >> configparms
+  echo "CXX += -fstack-protector-strong -D_FORTIFY_SOURCE=2" >> configparms
   make
 
   # remove harding in preparation to run test-suite
@@ -93,9 +103,13 @@ check() {
   # the linker commands need to be reordered - fixed in 2.19
   LDFLAGS=${LDFLAGS/--as-needed,/}
 
-  # there are known test failures on MIPS, as per the glibc release notes
   cd ${srcdir}/glibc-build
-  make check || echo "WARNING: make check failed, continuing anyway!"
+  
+  # ULP failures on i686 are all small and can be ignored
+  # tst-cleanupx4.out failure on i686 needs investigating...
+  #
+  # There are known test failures on MIPS, as per the glibc release notes
+  make -k check || true
 }
 
 package() {
